name: Integration Test
on: [push , pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@master
        with:
          ref: ${{github.ref}}
          
      - name: Docker Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}
          login-server: https://index.docker.io/v1/

      - name: Build Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          # Docker repository to tag the image with
          repository: mlspeclib/mlspeclib-action-sample-process-data
          tag_with_ref: True
          tag_with_sha: True
          push: False

      - name: Debugging with tmate
        uses: mxschmitt/action-tmate@v2

      - name: Test Image
        id: test_image_e2e
        run: |
          python3 -m unittest integration/test_e2e_integration.py
