name: Integration Test
on: [push , pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@master
        with:
          ref: ${{github.ref}}
          
      - name: Docker Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrects.DOCKERUSERNAME }}
          password: ${{ secrects.DOCKERPASSWORD }}
          login-server: https://index.docker.io/v1/
